Create Table APPS.T_DB_OPERATION_RECORDS
(
 INSPECT_ID Number Not Null,
 WH_ID Varchar2(10) Not Null,
 PO_NUMBER Varchar2(30) Not Null,
 LINE_NUMBER Varchar2(10) Not Null,
 ITEM_NUMBER Varchar2(30),
 ITEM_DESC Varchar2(60),
 VENDOR_CODE Varchar2(10),
 QUANTITY Number,
 UNQUALIFIED_QTY Number,
 REASON Varchar2(400),
 OBJECT_VERSION_NUMBER Number Default 1 Not Null,
 CREATION_DATE DATE default sysdate not null,
 CREATED_BY VARCHAR2(30) default '-1' not null,
 LAST_UPDATED_BY VARCHAR2(30) default '-1' not null,
 LAST_UPDATE_DATE DATE default sysdate not null,
 LAST_UPDATE_LOGIN VARCHAR2(30),
 ATTRIBUTE_CATEGORY VARCHAR2(30),
 ATTRIBUTE1 VARCHAR2(240),
 ATTRIBUTE2 VARCHAR2(240),
 ATTRIBUTE3 VARCHAR2(240),
 ATTRIBUTE4 VARCHAR2(240),
 ATTRIBUTE5 VARCHAR2(240),
 ATTRIBUTE6 VARCHAR2(240),
 ATTRIBUTE7 VARCHAR2(240),
 ATTRIBUTE8 VARCHAR2(240),
 ATTRIBUTE9 VARCHAR2(240),
 ATTRIBUTE10 VARCHAR2(240),
 ATTRIBUTE11 VARCHAR2(240),
 ATTRIBUTE12 VARCHAR2(240),
 ATTRIBUTE13 VARCHAR2(240),
 ATTRIBUTE14 VARCHAR2(240),
 ATTRIBUTE15 VARCHAR2(240)
) tablespace APPS_DATA;
comment on table APPS.T_DB_OPERATION_RECORDS is '数据库操作记录表';
comment on column APPS.T_DB_OPERATION_RECORDS.INSPECT_ID is '表ID，主键，供其他表做外键';
comment on column APPS.T_DB_OPERATION_RECORDS.WH_ID is '工厂号';
comment on column APPS.T_DB_OPERATION_RECORDS.PO_NUMBER is '订单编号';
comment on column APPS.T_DB_OPERATION_RECORDS.LINE_NUMBER is '行号';
comment on column APPS.T_DB_OPERATION_RECORDS.ITEM_NUMBER is '物料编号';
comment on column APPS.T_DB_OPERATION_RECORDS.ITEM_DESC is '物料描述';
comment on column APPS.T_DB_OPERATION_RECORDS.VENDOR_CODE is '供应商';
comment on column APPS.T_DB_OPERATION_RECORDS.QUANTITY is '数量';
comment on column APPS.T_DB_OPERATION_RECORDS.UNQUALIFIED_QTY is '不合格数量';
comment on column APPS.T_DB_OPERATION_RECORDS.REASON is '原因';
comment on column APPS.T_DB_OPERATION_RECORDS.OBJECT_VERSION_NUMBER is '行版本号，用来处理锁';

Create Unique Index APPS.T_DB_OPERATION_RECORDS_U1 On APPS.T_DB_OPERATION_RECORDS(INSPECT_ID) tablespace APPS_INDEX;
Create Index APPS.T_DB_OPERATION_RECORDS_N1 On APPS.T_DB_OPERATION_RECORDS(WH_ID,PO_NUMBER) tablespace APPS_INDEX;

Create Sequence APPS.T_DB_OPERATION_RECORDS_S Start With 10001;
    
